---
title: "Welcome to the ARCUS Modular Education Support System"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Many people at CHOP have become interested in R and statistical analysis in R. For Arcus Education, creating a learning environment where 100% of attendees spend 100% of their time working towards their _own_ goals at their own pace is of utmost importance. In our workshops each learner sets their own goals, receives an individualized curriculum based on those goals, and success is measured by the extent to which each learner meets their goals. Our workshop attendees have highly variable goals, which creates a challenge addressed by this system. 

Below you will find examples of this system in action. 

## R Beginner
Here is an example lesson plan for a user who is just getting started with R. It covers the absolute basics including classes, logic, functions and graphics.

[Example R Beginner Lesson Plan](http://www.a-mess.org/Personalized-Learning-Plan/?&modules=sHXtfjmhu84EQfHM7VpLV&curricula=qiJ&modulesplit=MTMsMA~~)

## Introduction to Statistics in R
The link below is to an example lesson plan for a user with some familiarity with R but who wants to learn to perform statistical analysis. It covers some fundamentals as well as practical application of statistical tests in R.

[Example Statistics Lesson Plan](http://www.a-mess.org/Personalized-Learning-Plan/?&modules=yoyXvAlV&curricula=qyR&modulesplit=NSww)

## Lessons in Other Programming Languages

Although our initial emphasis has been placed on the R programming language, we are cognizant that other languages and subjects need to be taught. Here is an extremely brief example of an exercise in Python. We continue to consider the optimal way to present other languages.

[Example Exercise in Python using pandas](http://www.a-mess.org/ic-python-demo/)

## Contribute Your Knowledge

